Added documentation for Apprise
borgmatic-collective/docker-borgmatic pull request #229
Opened 2023-05-05 10:20 UTC by jonathan8devs

Showing a way to use Appwrise in this project. NTFY didn't work for me and I stumbled across ticket #228 and the hint that Apprise is integrated with it. I would like to share this possibility with other users.

Closes #228

2023-05-31 12:48 UTC, grantbevis requested changes
Thanks for the PR but I'm not sure I agree with the approach.

2023-05-31 12:48 UTC, grantbevis commented on apprise/data/borgmatic.d/config.yaml
Should we edit the default config file we provide?

2023-05-31 12:48 UTC, grantbevis commented on apprise/data/borgmatic.d/config.yaml
> +        - echo "Starting a backup job."
Shouldn't this be an apprise command not an echo?

2023-09-01 05:07 UTC, closed without merging

2023-10-22 23:49 UTC, jonathan8devs commented
I revisited this topic recently as I am also writing for a German blog. The guide there was getting outdated, and I wanted to update it. The simplest way to set up a regular backup with log handling is as follows:

**Crontab.txt**
```bash
*/5 * * * * PATH=$PATH:/usr/local/bin /usr/local/bin/borgmatic --stats -v 0 > /tmp/backup_run.log
```

**Config.yaml**
```yaml
before_backup:
  - echo "Starting a backup job."
after_backup:
  - echo "Backup created."
  - apprise -vv -t "your-subdomain.example.com - BorgBackup" -b "$(cat /tmp/backup_run.log)" "mailtos://smtp.example.com:587?user=info@example.com&pass=YourSecurePassword&from=server@example.com"
on_error:
  - echo "Error while creating a backup."
```